"""游戏常量配置"""

# 窗口设置
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
CELL_SIZE = 20
GRID_WIDTH = WINDOW_WIDTH // CELL_SIZE   # 40
GRID_HEIGHT = WINDOW_HEIGHT // CELL_SIZE  # 30

# 帧率（用于界面渲染刷新，不是蛇的速度）
FPS = 60

# 颜色定义 (R, G, B)
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_GREEN = (0, 200, 0)
COLOR_GREEN_DARK = (0, 150, 0)
COLOR_GREEN_LIGHT = (0, 255, 100)
COLOR_RED = (200, 50, 50)
COLOR_DARK_RED = (120, 30, 30)
COLOR_YELLOW = (255, 255, 0)
COLOR_BLUE = (50, 100, 255)
COLOR_GRAY = (40, 40, 40)
COLOR_GRAY_LIGHT = (60, 60, 60)

# 蛇的设置
SNAKE_START_LENGTH = 3
SNAKE_START_X = GRID_WIDTH // 2
SNAKE_START_Y = GRID_HEIGHT // 2
SNAKE_START_DIRECTION = (1, 0)  # 初始向右

# 速度设置（毫秒/步）
BASE_SPEED = 150          # 初始速度
SPEED_INCREMENT = 10      # 每升一级减少的毫秒数
MIN_SPEED = 50            # 最快速度上限
FOODS_PER_LEVEL = 5       # 每吃 N 个食物升一级
SPEED_EFFECT_DURATION = 8  # 加速/减速效果持续时间（秒）
SPEED_EFFECT_AMOUNT = 30  # 速度效果影响量（毫秒）

# 食物设置
FOOD_NORMAL_CHANCE = 0.70
FOOD_SPEED_UP_CHANCE = 0.15
FOOD_SLOW_DOWN_CHANCE = 0.15
FOOD_NORMAL_SCORE = 10
FOOD_SPEED_UP_SCORE = 5
FOOD_SLOW_DOWN_SCORE = 5
FOOD_TIMED_DURATION = 8   # 限时食物持续时间（秒）

# 障碍物设置
OBSTACLE_COUNT = 8

# 方向向量
DIRECTION_UP = (0, -1)
DIRECTION_DOWN = (0, 1)
DIRECTION_LEFT = (-1, 0)
DIRECTION_RIGHT = (1, 0)

# 反向映射（用于防反向）
OPPOSITE_DIRECTIONS = {
    DIRECTION_UP: DIRECTION_DOWN,
    DIRECTION_DOWN: DIRECTION_UP,
    DIRECTION_LEFT: DIRECTION_RIGHT,
    DIRECTION_RIGHT: DIRECTION_LEFT,
}
